program BrokerTest;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  LoggingUnit in '..\Logging\LoggingUnit.pas',
  TextFileLoggerUnit in '..\Logging\TextFileLoggerUnit.pas',
  StripTaskUnit in '..\EntityClasses\strips\StripTaskUnit.pas',
  MonitoringTaskUnit in '..\EntityClasses\monitoring\MonitoringTaskUnit.pas',
  UniLoggerUnit in '..\Logging\UniLoggerUnit.pas',
  QueueUnit in '..\EntityClasses\router\QueueUnit.pas',
  RouterSourceUnit in '..\EntityClasses\router\RouterSourceUnit.pas',
  RuleUnit in '..\EntityClasses\router\RuleUnit.pas',
  SmallRuleUnit in '..\EntityClasses\router\SmallRuleUnit.pas',
  ConstsUnit in '..\Common\ConstsUnit.pas',
  FuncUnit in '..\Common\FuncUnit.pas',
  KeyValUnit in '..\Common\KeyValUnit.pas',
  ConnectionSettingsUnit in '..\EntityClasses\links\ConnectionSettingsUnit.pas',
  DirSettingsUnit in '..\EntityClasses\links\DirSettingsUnit.pas',
  LinkSettingsUnit in '..\EntityClasses\links\LinkSettingsUnit.pas',
  LinkUnit in '..\EntityClasses\links\LinkUnit.pas',
  QueueSettingsUnit in '..\EntityClasses\links\QueueSettingsUnit.pas',
  UserUnit in '..\EntityClasses\acl\UserUnit.pas',
  ParentLinkSettingEditFrameUnit in '..\Forms\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  SharedFrameBoolInput in '..\Forms\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  SharedFrameCombobox in '..\Forms\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameConnections in '..\Forms\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameQueue in '..\Forms\LinksFrames\SharedFrameQueue.pas' {FrameQueue: TUniFrame},
  SharedFrameTextInput in '..\Forms\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  SocketSpecialSettingEditFrameUnit in '..\Forms\LinksFrames\SocketSpecialSettingEditFrameUnit.pas' {SocketSpecialSettingEditFrame: TUniFrame},
  OpenMCEPSettingEditFrameUnit in '..\Forms\LinksFrames\OpenMCEPSettingEditFrameUnit.pas' {OpenMCEPSettingEditFrame: TUniFrame},
  ProfileUnit in '..\EntityClasses\datacomm\ProfileUnit.pas',
  S3SettingsUnit in '..\EntityClasses\links\S3SettingsUnit.pas',
  ScheduleSettingsUnit in '..\EntityClasses\links\ScheduleSettingsUnit.pas',
  ConditionUnit in '..\EntityClasses\Common\ConditionUnit.pas',
  EntityUnit in '..\EntityClasses\Common\EntityUnit.pas',
  FilterUnit in '..\EntityClasses\Common\FilterUnit.pas',
  GeoTypeUnit in '..\EntityClasses\Common\GeoTypeUnit.pas',
  GUIDListUnit in '..\EntityClasses\Common\GUIDListUnit.pas',
  StringListUnit in '..\EntityClasses\Common\StringListUnit.pas',
  StringUnit in '..\EntityClasses\Common\StringUnit.pas',
  TaskSettingsUnit in '..\EntityClasses\Common\TaskSettingsUnit.pas',
  TaskSourceUnit in '..\EntityClasses\Common\TaskSourceUnit.pas',
  TaskTypesUnit in '..\EntityClasses\Common\TaskTypesUnit.pas',
  TaskUnit in '..\EntityClasses\Common\TaskUnit.pas',
  SummaryTaskCustomSettingsUnit in '..\EntityClasses\summary\SummaryTaskCustomSettingsUnit.pas',
  SummaryTaskUnit in '..\EntityClasses\summary\SummaryTaskUnit.pas',
  ProfileFrameUnit in '..\Forms\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  ProfilesFrameUnit in '..\Forms\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  DirDownSettingEditFrameUnit in '..\Forms\LinksFrames\DirDownSettingEditFrameUnit.pas' {DirDownSettingEditFrame: TUniFrame},
  SharedFrameSchedule in '..\Forms\LinksFrames\SharedFrameSchedule.pas' {FrameSchedule: TUniFrame},
  SharedFrameS3 in '..\Forms\LinksFrames\SharedFrameS3.pas' {FrameS3: TUniFrame},
  DirUpSettingEditFrameUnit in '..\Forms\LinksFrames\DirUpSettingEditFrameUnit.pas' {DirUpSettingEditFrame: TUniFrame},
  FTPCliUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPCliUpLinkSettingEditFrameUnit.pas' {FTPCliUpLinkSettingEditFrame: TUniFrame},
  FTPCliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPCliDownLinkSettingEditFrameUnit.pas' {FtpCliDownLinkSettingEditFrame: TUniFrame},
  Pop3CliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\Pop3CliDownLinkSettingEditFrameUnit.pas' {Pop3CliDownLinkSettingEditFrame: TUniFrame},
  SMTPClieUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SMTPClieUpLinkSettingEditFrameUnit.pas' {SMTPClieUpLinkSettingEditFrame: TUniFrame},
  FTPServerDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPServerDownLinkSettingEditFrameUnit.pas' {FTPServerDownLinkSettingEditFrame: TUniFrame},
  FTPSrvUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPSrvUpLinkSettingEditFrameUnit.pas' {FTPSrvUpLinkSettingEditFrame: TUniFrame},
  SMTPSrvDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SMTPSrvDownLinkSettingEditFrameUnit.pas' {SMTPSrvDownLinkSettingEditFrame: TUniFrame},
  HTTPCliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\HTTPCliDownLinkSettingEditFrameUnit.pas' {HTTPCliDownLinkSettingEditFrame: TUniFrame},
  SebaSGSLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SebaSGSLinkSettingEditFrameUnit.pas' {SebaSGSLinkSettingEditFrame: TUniFrame},
  SebaCSDLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SebaCSDLinkSettingEditFrameUnit.pas' {SebaCSDLinkSettingEditFrame: TUniFrame},
  SharedFrameRuleConditionUnit in '..\Forms\LinksFrames\SharedFrameRuleConditionUnit.pas' {FrameRuleCondition: TUniFrame},
  ParentTaskCustomSettingsEditFrameUnit in '..\Forms\TasksFrames\ParentTaskCustomSettingsEditFrameUnit.pas' {ParentTaskCustomSettingsEditFrame: TUniFrame},
  SummaryCXMLTaskCustomSettingsEditFrameUnit in '..\Forms\TasksFrames\SummaryCXMLTaskCustomSettingsEditFrameUnit.pas' {SummaryCXMLTaskCustomSettingsEditFrame: TUniFrame},
  SummaryHydraTaskCustomSettingsEditFrameUnit in '..\Forms\TasksFrames\SummaryHydraTaskCustomSettingsEditFrameUnit.pas' {SummaryHydraTaskCustomSettingsEditFrame: TUniFrame},
  SummarySEBATaskCustomSettingsEditFrameUnit in '..\Forms\TasksFrames\SummarySEBATaskCustomSettingsEditFrameUnit.pas' {SummarySEBATaskCustomSettingsEditFrame: TUniFrame},
  SummarySynopTaskCustomSettingsEditFrameUnit in '..\Forms\TasksFrames\SummarySynopTaskCustomSettingsEditFrameUnit.pas' {SummarySynopTaskCustomSettingsEditFrame: TUniFrame},
  AbonentEditFormUnit in '..\Forms\AbonentEditFormUnit.pas' {AbonentEditForm: TUniForm},
  AbonentsFormUnit in '..\Forms\AbonentsFormUnit.pas' {AbonentsForm: TUniForm},
  AliasEditFormUnit in '..\Forms\AliasEditFormUnit.pas' {AliasEditForm: TUniForm},
  AliasesFormUnit in '..\Forms\AliasesFormUnit.pas' {AliasesForm: TUniForm},
  ChannelEditFormUnit in '..\Forms\ChannelEditFormUnit.pas' {ChannelEditForm: TUniForm},
  ChannelsFormUnit in '..\Forms\ChannelsFormUnit.pas' {ChannelsForm: TUniForm},
  DSProcessorTaskEditFormUnit in '..\Forms\DSProcessorTaskEditFormUnit.pas' {DSProcessorTaskEditForm: TUniForm},
  DSProcessorTasksFormUnit in '..\Forms\DSProcessorTasksFormUnit.pas' {DSProcessorTasksForm: TUniForm},
  LinkEditFormUnit in '..\Forms\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  LinkSettingsFormUnit in '..\Forms\LinkSettingsFormUnit.pas' {LinkSettingsForm: TUniForm},
  LinksFormUnit in '..\Forms\LinksFormUnit.pas' {LinksForm: TUniForm},
  ListParentFormUnit in '..\Forms\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  ParentEditFormUnit in '..\Forms\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in '..\Forms\ParentFormUnit.pas' {ParentForm: TUniForm},
  RouterSourceEditFormUnit in '..\Forms\RouterSourceEditFormUnit.pas' {RouterSourceEditForm: TUniForm},
  RouterSourcesFormUnit in '..\Forms\RouterSourcesFormUnit.pas' {RouterSourcesForm: TUniForm},
  SelectTaskSourcesFormUnit in '..\Forms\SelectTaskSourcesFormUnit.pas' {SelectTaskSourcesForm: TUniForm},
  StripTaskEditFormUnit in '..\Forms\StripTaskEditFormUnit.pas' {StripTaskEditForm: TUniForm},
  StripTasksFormUnit in '..\Forms\StripTasksFormUnit.pas' {StripTasksForm: TUniForm},
  SummaryTaskEditFormUnit in '..\Forms\SummaryTaskEditFormUnit.pas' {SummaryTaskEditForm: TUniForm},
  SummaryTasksFormUnit in '..\Forms\SummaryTasksFormUnit.pas' {SummaryTasksForm: TUniForm},
  TaskEditParentFormUnit in '..\Forms\TaskEditParentFormUnit.pas' {TaskEditParentForm: TUniForm},
  TasksParentFormUnit in '..\Forms\TasksParentFormUnit.pas' {TaskParentForm: TUniForm},
  AbonentUnit in '..\EntityClasses\router\AbonentUnit.pas',
  AliasUnit in '..\EntityClasses\router\AliasUnit.pas',
  ChannelUnit in '..\EntityClasses\router\ChannelUnit.pas',
  BindingUnit in '..\EntityClasses\dataserver\BindingUnit.pas',
  ContextTypeUnit in '..\EntityClasses\dataserver\ContextTypeUnit.pas',
  ContextUnit in '..\EntityClasses\dataserver\ContextUnit.pas',
  DataserieUnit in '..\EntityClasses\dataserver\DataserieUnit.pas',
  DsGroupUnit in '..\EntityClasses\dataserver\DsGroupUnit.pas',
  SourceCredsUnit in '..\EntityClasses\dataserver\SourceCredsUnit.pas',
  SourceTypeUnit in '..\EntityClasses\dataserver\SourceTypeUnit.pas',
  SourceUnit in '..\EntityClasses\dataserver\SourceUnit.pas',
  AbonensBrokerUnit in '..\APIClasses\AbonensBrokerUnit.pas',
  AbonentsBrokerUnit in '..\APIClasses\AbonentsBrokerUnit.pas',
  AliasesBrokerUnit in '..\APIClasses\AliasesBrokerUnit.pas',
  APIConst in '..\APIClasses\APIConst.pas',
  BindingsBrokerUnit in '..\APIClasses\BindingsBrokerUnit.pas',
  ChannelsBrokerUnit in '..\APIClasses\ChannelsBrokerUnit.pas',
  ContextsBrokerUnit in '..\APIClasses\ContextsBrokerUnit.pas',
  ContextTypesBrokerUnit in '..\APIClasses\ContextTypesBrokerUnit.pas',
  DsGroupsBrokerUnit in '..\APIClasses\DsGroupsBrokerUnit.pas',
  DSProcessorTasksBrokerUnit in '..\APIClasses\DSProcessorTasksBrokerUnit.pas',
  DSProcessorTaskSourceBrokerUnit in '..\APIClasses\DSProcessorTaskSourceBrokerUnit.pas',
  EntityBrokerUnit in '..\APIClasses\EntityBrokerUnit.pas',
  FieldSetBrokerUnit in '..\APIClasses\FieldSetBrokerUnit.pas',
  HttpRequestUnit in '..\APIClasses\HttpRequestUnit.pas',
  LinksBrokerUnit in '..\APIClasses\LinksBrokerUnit.pas',
  MainHttpModuleUnit in '..\APIClasses\MainHttpModuleUnit.pas',
  MonitoringTasksBrokerUnit in '..\APIClasses\MonitoringTasksBrokerUnit.pas',
  MonitoringTaskSourceBrokerUnit in '..\APIClasses\MonitoringTaskSourceBrokerUnit.pas',
  ParentBrokerUnit in '..\APIClasses\ParentBrokerUnit.pas',
  ProfilesBrokerUnit in '..\APIClasses\ProfilesBrokerUnit.pas',
  QueuesBrokerUnit in '..\APIClasses\QueuesBrokerUnit.pas',
  RouterSourceBrokerUnit in '..\APIClasses\RouterSourceBrokerUnit.pas',
  RulesBrokerUnit in '..\APIClasses\RulesBrokerUnit.pas',
  SourceCredsBrokerUnit in '..\APIClasses\SourceCredsBrokerUnit.pas',
  SourcesBrokerUnit in '..\APIClasses\SourcesBrokerUnit.pas',
  SourceTypesBrokerUnit in '..\APIClasses\SourceTypesBrokerUnit.pas',
  StripTasksBrokerUnit in '..\APIClasses\StripTasksBrokerUnit.pas',
  StripTaskSourceBrokerUnit in '..\APIClasses\StripTaskSourceBrokerUnit.pas',
  SummaryTasksBrokerUnit in '..\APIClasses\SummaryTasksBrokerUnit.pas',
  SummaryTaskSourcesBrokerUnit in '..\APIClasses\SummaryTaskSourcesBrokerUnit.pas',
  TasksBrokerUnit in '..\APIClasses\TasksBrokerUnit.pas',
  TaskSourcesBrokerUnit in '..\APIClasses\TaskSourcesBrokerUnit.pas',
  TaskTypesBrokerUnit in '..\APIClasses\TaskTypesBrokerUnit.pas',
  UsersBrokerUnit in '..\APIClasses\UsersBrokerUnit.pas',
  DSProcessorTaskUnit in '..\EntityClasses\dsprocessor\DSProcessorTaskUnit.pas',
  common in '..\Common\common.pas',
  LinkFrameUtils in '..\Forms\LinksFrames\LinkFrameUtils.pas',
  QueueFrameUnit in '..\Forms\QueueFrameUnit.pas' {QueueFrame: TUniFrame},
  ProfileRuleUnit in '..\EntityClasses\acl\ProfileRuleUnit.pas',
  SharedFrameQueueFilterUnit in '..\Forms\SharedFrameQueueFilterUnit.pas' {QueueConditionFrame: TUniFrame};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
