program BrokerTest;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  LoggingUnit in '..\Logging\LoggingUnit.pas',
  TextFileLoggerUnit in '..\Logging\TextFileLoggerUnit.pas',
  StripTaskUnit in '..\EntityClasses\strips\StripTaskUnit.pas',
  MonitoringTaskUnit in '..\EntityClasses\monitoring\MonitoringTaskUnit.pas',
  UniLoggerUnit in '..\Logging\UniLoggerUnit.pas',
  AliasEditFormUnit in '..\Forms\AliasEditFormUnit.pas' {AliasEditForm: TUniForm},
  AliasesFormUnit in '..\Forms\AliasesFormUnit.pas' {AliasesForm: TUniForm},
  ChannelEditFormUnit in '..\Forms\ChannelEditFormUnit.pas' {ChannelEditForm: TUniForm},
  ChannelsFormUnit in '..\Forms\ChannelsFormUnit.pas' {ChannelsForm: TUniForm},
  LinkEditFormUnit in '..\Forms\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  LinkSettingsFormUnit in '..\Forms\LinkSettingsFormUnit.pas' {LinkSettingsForm: TUniForm},
  LinksFormUnit in '..\Forms\LinksFormUnit.pas' {LinksForm: TUniForm},
  ListParentFormUnit in '..\Forms\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  ParentEditFormUnit in '..\Forms\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in '..\Forms\ParentFormUnit.pas' {ParentForm: TUniForm},
  RouterSourceEditFormUnit in '..\Forms\RouterSourceEditFormUnit.pas' {RouterSourceEditForm: TUniForm},
  RouterSourcesFormUnit in '..\Forms\RouterSourcesFormUnit.pas' {RouterSourcesForm: TUniForm},
  StripTaskEditFormUnit in '..\Forms\StripTaskEditFormUnit.pas' {StripTaskEditForm: TUniForm},
  StripTasksFormUnit in '..\Forms\StripTasksFormUnit.pas' {StripTasksForm: TUniForm},
  SummaryTaskEditFormUnit in '..\Forms\SummaryTaskEditFormUnit.pas' {SummaryTaskEditForm: TUniForm},
  SummaryTasksFormUnit in '..\Forms\SummaryTasksFormUnit.pas' {SummaryTasksForm: TUniForm},
  AliasUnit in '..\EntityClasses\router\AliasUnit.pas',
  ChannelUnit in '..\EntityClasses\router\ChannelUnit.pas',
  QueueUnit in '..\EntityClasses\router\QueueUnit.pas',
  RouterSourceUnit in '..\EntityClasses\router\RouterSourceUnit.pas',
  RuleUnit in '..\EntityClasses\router\RuleUnit.pas',
  SmallRuleUnit in '..\EntityClasses\router\SmallRuleUnit.pas',
  ConstsUnit in '..\Common\ConstsUnit.pas',
  FuncUnit in '..\Common\FuncUnit.pas',
  KeyValUnit in '..\Common\KeyValUnit.pas',
  ConnectionSettingsUnit in '..\EntityClasses\links\ConnectionSettingsUnit.pas',
  DirSettingsUnit in '..\EntityClasses\links\DirSettingsUnit.pas',
  LinkSettingsUnit in '..\EntityClasses\links\LinkSettingsUnit.pas',
  LinkUnit in '..\EntityClasses\links\LinkUnit.pas',
  QueueSettingsUnit in '..\EntityClasses\links\QueueSettingsUnit.pas',
  DataserieUnit in '..\EntityClasses\dataserver\DataserieUnit.pas',
  DsGroupUnit in '..\EntityClasses\dataserver\DsGroupUnit.pas',
  SourceCredsUnit in '..\EntityClasses\dataserver\SourceCredsUnit.pas',
  UserUnit in '..\EntityClasses\acl\UserUnit.pas',
  ParentLinkSettingEditFrameUnit in '..\Forms\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  SharedFrameBoolInput in '..\Forms\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  SharedFrameCombobox in '..\Forms\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameConnections in '..\Forms\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameQueue in '..\Forms\LinksFrames\SharedFrameQueue.pas' {FrameQueue: TUniFrame},
  SharedFrameTextInput in '..\Forms\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  SocketSpecialSettingEditFrameUnit in '..\Forms\LinksFrames\SocketSpecialSettingEditFrameUnit.pas' {SocketSpecialSettingEditFrame: TUniFrame},
  OpenMCEPSettingEditFrameUnit in '..\Forms\LinksFrames\OpenMCEPSettingEditFrameUnit.pas' {OpenMCEPSettingEditFrame: TUniFrame},
  ProfileUnit in '..\EntityClasses\datacomm\ProfileUnit.pas',
  AliasesBrokerUnit in '..\APIClasses\AliasesBrokerUnit.pas',
  APIConst in '..\APIClasses\APIConst.pas',
  ChannelsBrokerUnit in '..\APIClasses\ChannelsBrokerUnit.pas',
  DsGroupsBrokerUnit in '..\APIClasses\DsGroupsBrokerUnit.pas',
  EntityBrokerUnit in '..\APIClasses\EntityBrokerUnit.pas',
  FieldSetBrokerUnit in '..\APIClasses\FieldSetBrokerUnit.pas',
  LinksBrokerUnit in '..\APIClasses\LinksBrokerUnit.pas',
  MainHttpModuleUnit in '..\APIClasses\MainHttpModuleUnit.pas',
  MonitoringTasksBrokerUnit in '..\APIClasses\MonitoringTasksBrokerUnit.pas',
  MonitoringTaskSourceBrokerUnit in '..\APIClasses\MonitoringTaskSourceBrokerUnit.pas',
  ParentBrokerUnit in '..\APIClasses\ParentBrokerUnit.pas',
  ProfilesBrokerUnit in '..\APIClasses\ProfilesBrokerUnit.pas',
  QueuesBrokerUnit in '..\APIClasses\QueuesBrokerUnit.pas',
  RouterSourceBrokerUnit in '..\APIClasses\RouterSourceBrokerUnit.pas',
  RulesBrokerUnit in '..\APIClasses\RulesBrokerUnit.pas',
  SourceCredsBrokerUnit in '..\APIClasses\SourceCredsBrokerUnit.pas',
  StripTasksBrokerUnit in '..\APIClasses\StripTasksBrokerUnit.pas',
  StripTaskSourceBrokerUnit in '..\APIClasses\StripTaskSourceBrokerUnit.pas',
  SummaryTasksBrokerUnit in '..\APIClasses\SummaryTasksBrokerUnit.pas',
  SummaryTaskSourcesBrokerUnit in '..\APIClasses\SummaryTaskSourcesBrokerUnit.pas',
  TasksBrokerUnit in '..\APIClasses\TasksBrokerUnit.pas',
  TaskSourceBrokerUnit in '..\APIClasses\TaskSourceBrokerUnit.pas',
  TaskSourcesBrokerUnit in '..\APIClasses\TaskSourcesBrokerUnit.pas',
  TaskTypesBrokerUnit in '..\APIClasses\TaskTypesBrokerUnit.pas',
  UsersBrokerUnit in '..\APIClasses\UsersBrokerUnit.pas',
  S3SettingsUnit in '..\EntityClasses\links\S3SettingsUnit.pas',
  ScheduleSettingsUnit in '..\EntityClasses\links\ScheduleSettingsUnit.pas',
  ConditionUnit in '..\EntityClasses\Common\ConditionUnit.pas',
  EntityUnit in '..\EntityClasses\Common\EntityUnit.pas',
  FilterUnit in '..\EntityClasses\Common\FilterUnit.pas',
  GeoTypeUnit in '..\EntityClasses\Common\GeoTypeUnit.pas',
  GUIDListUnit in '..\EntityClasses\Common\GUIDListUnit.pas',
  StringListUnit in '..\EntityClasses\Common\StringListUnit.pas',
  StringUnit in '..\EntityClasses\Common\StringUnit.pas',
  TaskSettingsUnit in '..\EntityClasses\Common\TaskSettingsUnit.pas',
  TaskSourceUnit in '..\EntityClasses\Common\TaskSourceUnit.pas',
  TaskTypesUnit in '..\EntityClasses\Common\TaskTypesUnit.pas',
  TaskUnit in '..\EntityClasses\Common\TaskUnit.pas',
  SummaryTaskCustomSettingsUnit in '..\EntityClasses\summary\SummaryTaskCustomSettingsUnit.pas',
  SummaryTaskUnit in '..\EntityClasses\summary\SummaryTaskUnit.pas',
  ProfileFrameUnit in '..\Forms\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  ProfilesFrameUnit in '..\Forms\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  DirDownSettingEditFrameUnit in '..\Forms\LinksFrames\DirDownSettingEditFrameUnit.pas' {DirDownSettingEditFrame: TUniFrame},
  SharedFrameSchedule in '..\Forms\LinksFrames\SharedFrameSchedule.pas' {FrameSchedule: TUniFrame},
  SharedFrameS3 in '..\Forms\LinksFrames\SharedFrameS3.pas' {FrameS3: TUniFrame},
  DirUpSettingEditFrameUnit in '..\Forms\LinksFrames\DirUpSettingEditFrameUnit.pas' {DirUpSettingEditFrame: TUniFrame},
  FTPCliUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPCliUpLinkSettingEditFrameUnit.pas' {FTPCliUpLinkSettingEditFrame: TUniFrame},
  FTPCliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPCliDownLinkSettingEditFrameUnit.pas' {FtpCliDownLinkSettingEditFrame: TUniFrame},
  Pop3CliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\Pop3CliDownLinkSettingEditFrameUnit.pas' {Pop3CliDownLinkSettingEditFrame: TUniFrame},
  SMTPClieUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SMTPClieUpLinkSettingEditFrameUnit.pas' {SMTPClieUpLinkSettingEditFrame: TUniFrame},
  FTPServerDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPServerDownLinkSettingEditFrameUnit.pas' {FTPServerDownLinkSettingEditFrame: TUniFrame},
  FTPSrvUpLinkSettingEditFrameUnit in '..\Forms\LinksFrames\FTPSrvUpLinkSettingEditFrameUnit.pas' {FTPSrvUpLinkSettingEditFrame: TUniFrame},
  SMTPSrvDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SMTPSrvDownLinkSettingEditFrameUnit.pas' {SMTPSrvDownLinkSettingEditFrame: TUniFrame},
  HTTPCliDownLinkSettingEditFrameUnit in '..\Forms\LinksFrames\HTTPCliDownLinkSettingEditFrameUnit.pas' {HTTPCliDownLinkSettingEditFrame: TUniFrame},
  SebaSGSLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SebaSGSLinkSettingEditFrameUnit.pas' {SebaSGSLinkSettingEditFrame: TUniFrame},
  SebaCSDLinkSettingEditFrameUnit in '..\Forms\LinksFrames\SebaCSDLinkSettingEditFrameUnit.pas' {SebaCSDLinkSettingEditFrame: TUniFrame},
  SharedFrameRuleConditionUnit in '..\Forms\LinksFrames\SharedFrameRuleConditionUnit.pas' {FrameRuleCondition: TUniFrame};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
