object MainForm: TMainForm
  Left = 0
  Top = 0
  ClientHeight = 696
  ClientWidth = 700
  Caption = 'MainForm'
  OldCreateOrder = False
  MonitoredKeys.Keys = <>
  TextHeight = 15
  object ShowMemo: TUniMemo
    AlignWithMargins = True
    Left = 159
    Top = 3
    Width = 538
    Height = 690
    Hint = ''
    ScrollBars = ssBoth
    Align = alClient
    TabOrder = 0
    ExplicitWidth = 530
    ExplicitHeight = 469
  end
  object sbTestButtons: TUniScrollBox
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 150
    Height = 690
    Hint = ''
    Align = alLeft
    TabOrder = 1
    ScrollDirection = sdVertical
    ExplicitHeight = 469
    ScrollHeight = 615
    object gbLinks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 5
      Width = 138
      Height = 85
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = ' Links '
      Align = alTop
      TabOrder = 0
      ExplicitWidth = 108
      object btnLinskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnLinskListClick
        ExplicitWidth = 84
      end
      object btnLinkInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnLinkInfoClick
        ExplicitWidth = 84
      end
    end
    object gbQueues: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 100
      Width = 138
      Height = 85
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = ' Queues '
      Align = alTop
      TabOrder = 1
      ExplicitWidth = 108
      object btnQueuesList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnQueuesListClick
        ExplicitWidth = 84
      end
      object btnQueuesInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnQueuesInfoClick
        ExplicitWidth = 84
      end
    end
    object gbStripTasks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 195
      Width = 138
      Height = 205
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = ' Strip.Tasks '
      Align = alTop
      TabOrder = 2
      ExplicitWidth = 108
      object btnStripTaskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnStripTaskListClick
        ExplicitWidth = 84
      end
      object btnStripTaskInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 80
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnStripTaskInfoClick
        ExplicitWidth = 84
      end
      object btnStripTaskNew: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 110
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'New'
        Align = alTop
        TabOrder = 3
        OnClick = btnStripTaskNewClick
        ExplicitWidth = 84
      end
      object btnStripTaskUpdate: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 140
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Update'
        Align = alTop
        TabOrder = 4
        OnClick = btnStripTaskUpdateClick
        ExplicitWidth = 84
      end
      object btnStripTaskRemove: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 170
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Remove'
        Align = alTop
        TabOrder = 5
        OnClick = btnStripTaskRemoveClick
        ExplicitWidth = 84
      end
      object btnStripTasks: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'StripTasks'
        Align = alTop
        TabOrder = 6
        OnClick = btnStripTasksClick
        ExplicitWidth = 84
      end
    end
    object gbSummaryTasks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 410
      Width = 138
      Height = 205
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = ' Summary.Tasks '
      Align = alTop
      TabOrder = 3
      ExplicitWidth = 108
      object btnSummaryTaskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnSummaryTaskListClick
        ExplicitWidth = 84
      end
      object btnSummaryTaskInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnSummaryTaskInfoClick
        ExplicitWidth = 84
      end
      object btnSummaryTaskNew: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 80
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'New'
        Align = alTop
        TabOrder = 3
        OnClick = btnSummaryTaskNewClick
        ExplicitWidth = 84
      end
      object btnSummaryTaskUpdate: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 110
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Update'
        Align = alTop
        TabOrder = 4
        OnClick = btnSummaryTaskUpdateClick
        ExplicitWidth = 84
      end
      object btnSummaryTaskRemove: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 140
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Remove'
        Align = alTop
        TabOrder = 5
        OnClick = btnSummaryTaskRemoveClick
        ExplicitWidth = 84
      end
      object btnSummaryTaskTypes: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 170
        Width = 114
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Types'
        Align = alTop
        TabOrder = 6
        OnClick = btnSummaryTaskTypesClick
        ExplicitWidth = 84
      end
    end
  end
end
