object MainForm: TMainForm
  Left = 0
  Top = 0
  ClientHeight = 500
  ClientWidth = 700
  Caption = 'MainForm'
  OnShow = UniFormShow
  OldCreateOrder = False
  MonitoredKeys.Keys = <>
  TextHeight = 15
  object sbTestButtons: TUniScrollBox
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 160
    Height = 494
    Hint = ''
    Align = alLeft
    TabOrder = 0
    ScrollDirection = sdVertical
    ExplicitHeight = 486
    ScrollHeight = 749
    object gbLinks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 5
      Width = 117
      Height = 124
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 15
      Margins.Bottom = 5
      Caption = ' Links '
      Align = alTop
      TabOrder = 0
      object btnLinskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnLinskListClick
      end
      object btnLinkInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnLinkInfoClick
      end
      object btnLinkSettings: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 80
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Settings'
        Align = alTop
        TabOrder = 3
        OnClick = btnLinkSettingsClick
      end
    end
    object gbQueues: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 234
      Width = 117
      Height = 85
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 15
      Margins.Bottom = 5
      Caption = ' Queues '
      Align = alTop
      TabOrder = 1
      object btnQueuesList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnQueuesListClick
      end
      object btnQueuesInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnQueuesInfoClick
      end
    end
    object gbStripTasks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 329
      Width = 117
      Height = 205
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 15
      Margins.Bottom = 5
      Caption = ' Strip.Tasks '
      Align = alTop
      TabOrder = 2
      object btnStripTaskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnStripTaskListClick
      end
      object btnStripTaskInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 80
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnStripTaskInfoClick
      end
      object btnStripTaskNew: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 110
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'New'
        Align = alTop
        TabOrder = 3
        OnClick = btnStripTaskNewClick
      end
      object btnStripTaskUpdate: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 140
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Update'
        Align = alTop
        TabOrder = 4
        OnClick = btnStripTaskUpdateClick
      end
      object btnStripTaskRemove: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 170
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Remove'
        Align = alTop
        TabOrder = 5
        OnClick = btnStripTaskRemoveClick
      end
      object btnStripTasks: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'StripTasks'
        Align = alTop
        TabOrder = 6
        OnClick = btnStripTasksClick
      end
    end
    object gbSummaryTasks: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 544
      Width = 117
      Height = 205
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 15
      Margins.Bottom = 5
      Caption = ' Summary.Tasks '
      Align = alTop
      TabOrder = 3
      object btnSummaryTaskList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnSummaryTaskListClick
      end
      object btnSummaryTaskInfo: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 80
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Info'
        Align = alTop
        TabOrder = 2
        OnClick = btnSummaryTaskInfoClick
      end
      object btnSummaryTaskNew: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 110
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'New'
        Align = alTop
        TabOrder = 3
        OnClick = btnSummaryTaskNewClick
      end
      object btnSummaryTaskUpdate: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 140
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Update'
        Align = alTop
        TabOrder = 4
        OnClick = btnSummaryTaskUpdateClick
      end
      object btnSummaryTaskRemove: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 170
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Remove'
        Align = alTop
        TabOrder = 5
        OnClick = btnSummaryTaskRemoveClick
      end
      object btnSummaryTaskTypes: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 200
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Types'
        Align = alTop
        TabOrder = 6
      end
      object btnSummaryTasks: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'SummaryTasks'
        Align = alTop
        TabOrder = 7
        OnClick = btnSummaryTasksClick
      end
    end
    object UniGroupBox1: TUniGroupBox
      AlignWithMargins = True
      Left = 5
      Top = 139
      Width = 117
      Height = 85
      Hint = ''
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 15
      Margins.Bottom = 5
      Caption = ' Channels '
      Align = alTop
      TabOrder = 4
      object btnChannelsList: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 20
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'List'
        Align = alTop
        TabOrder = 1
        OnClick = btnChannelsListClick
        ExplicitLeft = 10
        ExplicitTop = 5
      end
      object btnChannelsForm: TUniButton
        AlignWithMargins = True
        Left = 12
        Top = 50
        Width = 93
        Height = 25
        Hint = ''
        Margins.Left = 10
        Margins.Top = 5
        Margins.Right = 10
        Margins.Bottom = 0
        Caption = 'Form'
        Align = alTop
        TabOrder = 2
        OnClick = btnChannelsFormClick
        ExplicitLeft = 20
        ExplicitTop = 28
      end
    end
  end
  object UniPanel1: TUniPanel
    Left = 166
    Top = 0
    Width = 534
    Height = 500
    Hint = ''
    Align = alClient
    TabOrder = 1
    Caption = 'UniPanel1'
    ExplicitWidth = 532
    ExplicitHeight = 492
    object ShowMemo: TUniMemo
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 526
      Height = 403
      Hint = ''
      ScrollBars = ssBoth
      Align = alClient
      TabOrder = 1
      ExplicitWidth = 524
      ExplicitHeight = 395
    end
    object LogMemo: TUniMemo
      AlignWithMargins = True
      Left = 4
      Top = 413
      Width = 526
      Height = 83
      Hint = ''
      ScrollBars = ssBoth
      Align = alBottom
      ReadOnly = True
      TabOrder = 2
      ExplicitTop = 405
      ExplicitWidth = 524
    end
  end
end
