program FrontMSS;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  LoggingUnit in 'Logging\LoggingUnit.pas',
  TextFileLoggerUnit in 'Logging\TextFileLoggerUnit.pas',
  ChannelEditFormUnit in 'Forms\ChannelEditFormUnit.pas' {ChannelEditForm: TUniForm},
  ChannelsFormUnit in 'Forms\ChannelsFormUnit.pas' {ChannelsForm: TUniForm},
  ListParentFormUnit in 'Forms\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  ParentEditFormUnit in 'Forms\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in 'Forms\ParentFormUnit.pas' {ParentForm: TUniForm},
  StripTaskEditFormUnit in 'Forms\StripTaskEditFormUnit.pas' {StripTaskEditForm: TUniForm},
  StripTasksFormUnit in 'Forms\StripTasksFormUnit.pas' {StripTasksForm: TUniForm},
  AliasEditFormUnit in 'Forms\AliasEditFormUnit.pas' {AliasEditForm: TUniForm},
  AliasesFormUnit in 'Forms\AliasesFormUnit.pas' {AliasesForm: TUniForm},
  AbonentEditFormUnit in 'Forms\AbonentEditFormUnit.pas' {AbonentEditForm: TUniForm},
  AbonentsFormUnit in 'Forms\AbonentsFormUnit.pas' {AbonentsForm: TUniForm},
  RouterSourceEditFormUnit in 'Forms\RouterSourceEditFormUnit.pas' {RouterSourceEditForm: TUniForm},
  RouterSourcesFormUnit in 'Forms\RouterSourcesFormUnit.pas' {RouterSourcesForm: TUniForm},
  APIConst in 'APIClasses\APIConst.pas',
  ChannelsBrokerUnit in 'APIClasses\ChannelsBrokerUnit.pas',
  LinksBrokerUnit in 'APIClasses\LinksBrokerUnit.pas',
  MonitoringTasksBrokerUnit in 'APIClasses\MonitoringTasksBrokerUnit.pas',
  QueuesBrokerUnit in 'APIClasses\QueuesBrokerUnit.pas',
  RouterSourceBrokerUnit in 'APIClasses\RouterSourceBrokerUnit.pas',
  AbonentsBrokerUnit in 'APIClasses\AbonentsBrokerUnit.pas',
  AliasesBrokerUnit in 'APIClasses\AliasesBrokerUnit.pas',
  StripTasksBrokerUnit in 'APIClasses\StripTasksBrokerUnit.pas',
  SummaryTasksBrokerUnit in 'APIClasses\SummaryTasksBrokerUnit.pas',
  MonitoringTaskUnit in 'EntityClasses\monitoring\MonitoringTaskUnit.pas',
  StripTaskUnit in 'EntityClasses\strips\StripTaskUnit.pas',
  ChannelUnit in 'EntityClasses\router\ChannelUnit.pas',
  AliasUnit in 'EntityClasses\router\AliasUnit.pas',
  AbonentUnit in 'EntityClasses\router\AbonentUnit.pas',
  QueueUnit in 'EntityClasses\router\QueueUnit.pas',
  RouterSourceUnit in 'EntityClasses\router\RouterSourceUnit.pas',
  MainHttpModuleUnit in 'APIClasses\MainHttpModuleUnit.pas',
  LinksFormUnit in 'Forms\LinksFormUnit.pas' {LinksForm: TUniForm},
  LinkEditFormUnit in 'Forms\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  SummaryTaskEditFormUnit in 'Forms\SummaryTaskEditFormUnit.pas',
  SummaryTasksFormUnit in 'Forms\SummaryTasksFormUnit.pas',
  EntityBrokerUnit in 'APIClasses\EntityBrokerUnit.pas',
  ConstsUnit in 'Common\ConstsUnit.pas',
  FuncUnit in 'Common\FuncUnit.pas',
  KeyValUnit in 'Common\KeyValUnit.pas',
  ParentTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\ParentTaskCustomSettingsEditFrameUnit.pas' {ParentTaskCustomSettingsEditFrame: TUniFrame},
  ConditionUnit in 'EntityClasses\Common\ConditionUnit.pas',
  EntityUnit in 'EntityClasses\Common\EntityUnit.pas',
  FilterUnit in 'EntityClasses\Common\FilterUnit.pas',
  GeoTypeUnit in 'EntityClasses\Common\GeoTypeUnit.pas',
  GUIDListUnit in 'EntityClasses\Common\GUIDListUnit.pas',
  StringListUnit in 'EntityClasses\Common\StringListUnit.pas',
  StringUnit in 'EntityClasses\Common\StringUnit.pas',
  TaskSettingsUnit in 'EntityClasses\tasks\TaskSettingsUnit.pas',
  TaskSourceUnit in 'EntityClasses\tasks\TaskSourceUnit.pas',
  TaskTypesUnit in 'EntityClasses\tasks\TaskTypesUnit.pas',
  TaskUnit in 'EntityClasses\tasks\TaskUnit.pas',
  ConnectionSettingsUnit in 'EntityClasses\links\ConnectionSettingsUnit.pas',
  DirSettingsUnit in 'EntityClasses\links\DirSettingsUnit.pas',
  LinkSettingsUnit in 'EntityClasses\links\LinkSettingsUnit.pas',
  LinkUnit in 'EntityClasses\links\LinkUnit.pas',
  QueueSettingsUnit in 'EntityClasses\links\QueueSettingsUnit.pas',
  S3SettingsUnit in 'EntityClasses\links\S3SettingsUnit.pas',
  ScheduleSettingsUnit in 'EntityClasses\links\ScheduleSettingsUnit.pas',
  SummaryTaskCustomSettingsUnit in 'EntityClasses\summary\SummaryTaskCustomSettingsUnit.pas',
  SummaryTaskUnit in 'EntityClasses\summary\SummaryTaskUnit.pas',
  SummaryCXMLTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummaryCXMLTaskCustomSettingsEditFrameUnit.pas' {SummaryCXMLTaskCustomSettingsEditFrame: TUniFrame},
  SummarySynopTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummarySynopTaskCustomSettingsEditFrameUnit.pas' {SummarySynopTaskCustomSettingsEditFrame: TUniFrame},
  SummaryHydraTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummaryHydraTaskCustomSettingsEditFrameUnit.pas' {SummaryHydraTaskCustomSettingsEditFrame: TUniFrame},
  SummarySEBATaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummarySEBATaskCustomSettingsEditFrameUnit.pas' {SummarySEBATaskCustomSettingsEditFrame: TUniFrame},
  ProfileUnit in 'EntityClasses\datacomm\ProfileUnit.pas',
  RuleUnit in 'EntityClasses\router\RuleUnit.pas',
  SmallRuleUnit in 'EntityClasses\router\SmallRuleUnit.pas',
  ProfilesBrokerUnit in 'APIClasses\ProfilesBrokerUnit.pas',
  OpenMCEPSettingEditFrameUnit in 'Forms\LinksFrames\OpenMCEPSettingEditFrameUnit.pas' {OpenMCEPSettingEditFrame: TUniFrame},
  ParentLinkSettingEditFrameUnit in 'Forms\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  ProfileFrameUnit in 'Forms\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  ProfilesFrameUnit in 'Forms\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  SharedFrameBoolInput in 'Forms\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  SharedFrameCombobox in 'Forms\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameConnections in 'Forms\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameQueue in 'Forms\LinksFrames\SharedFrameQueue.pas' {FrameQueue: TUniFrame},
  SharedFrameTextInput in 'Forms\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  SocketSpecialSettingEditFrameUnit in 'Forms\LinksFrames\SocketSpecialSettingEditFrameUnit.pas' {SocketSpecialSettingEditFrame: TUniFrame},
  SummaryTaskSourcesBrokerUnit in 'APIClasses\SummaryTaskSourcesBrokerUnit.pas',
  TasksBrokerUnit in 'APIClasses\TasksBrokerUnit.pas',
  TaskSourcesBrokerUnit in 'APIClasses\TaskSourcesBrokerUnit.pas',
  DSProcessorTaskUnit in 'EntityClasses\dsprocessor\DSProcessorTaskUnit.pas';

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
