program FrontMSS;




uses
  Forms,
  APIConst in 'APIClasses\APIConst.pas',
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  LoggingUnit in 'Logging\LoggingUnit.pas',
  TextFileLoggerUnit in 'Logging\TextFileLoggerUnit.pas',
  ChannelEditFormUnit in 'Forms\ChannelEditFormUnit.pas' {ChannelEditForm: TUniForm},
  ChannelsFormUnit in 'Forms\ChannelsFormUnit.pas' {ChannelsForm: TUniForm},
  QueueEditFormUnit in 'Forms\QueueEditFormUnit.pas' {QueueEditForm: TUniForm},
  QueuesFormUnit in 'Forms\QueuesFormUnit.pas' {QueuesForm: TUniForm},
  ListParentFormUnit in 'Forms\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  ParentEditFormUnit in 'Forms\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in 'Forms\ParentFormUnit.pas' {ParentForm: TUniForm},
  StripTaskEditFormUnit in 'Forms\StripTaskEditFormUnit.pas' {StripTaskEditForm: TUniForm},
  StripTasksFormUnit in 'Forms\StripTasksFormUnit.pas' {StripTasksForm: TUniForm},
  AliasEditFormUnit in 'Forms\AliasEditFormUnit.pas' {AliasEditForm: TUniForm},
  AliasesFormUnit in 'Forms\AliasesFormUnit.pas' {AliasesForm: TUniForm},
  AbonentEditFormUnit in 'Forms\AbonentEditFormUnit.pas' {AbonentEditForm: TUniForm},
  AbonentsFormUnit in 'Forms\AbonentsFormUnit.pas' {AbonentsForm: TUniForm},
  HandlerEditFormUnit in 'Forms\HandlerEditFormUnit.pas' {HandlerEditForm: TUniForm},
  HandlersFormUnit in 'Forms\HandlersFormUnit.pas' {HandlersForm: TUniForm},
  RouterSourceEditFormUnit in 'Forms\RouterSourceEditFormUnit.pas' {RouterSourceEditForm: TUniForm},
  RouterSourcesFormUnit in 'Forms\RouterSourcesFormUnit.pas' {RouterSourcesForm: TUniForm},
  RuleEditFormUnit in 'Forms\RuleEditFormUnit.pas' {RuleEditForm: TUniForm},
  RulesFormUnit in 'Forms\RulesFormUnit.pas' {RulesForm: TUniForm},
  MonitoringTaskUnit in 'EntityClasses\monitoring\MonitoringTaskUnit.pas',
  StripTaskUnit in 'EntityClasses\strips\StripTaskUnit.pas',
  ChannelUnit in 'EntityClasses\router\ChannelUnit.pas',
  AliasUnit in 'EntityClasses\router\AliasUnit.pas',
  AbonentUnit in 'EntityClasses\router\AbonentUnit.pas',
  HandlerUnit in 'EntityClasses\router\HandlerUnit.pas',
  QueueUnit in 'EntityClasses\router\QueueUnit.pas',
  RouterSourceUnit in 'EntityClasses\router\RouterSourceUnit.pas',
  MainHttpModuleUnit in 'APIClasses\Legacy\MainHttpModuleUnit.pas',
  LinksFormUnit in 'Forms\LinksFormUnit.pas' {LinksForm: TUniForm},
  LinkEditFormUnit in 'Forms\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  SummaryTaskEditFormUnit in 'Forms\SummaryTaskEditFormUnit.pas',
  SummaryTasksFormUnit in 'Forms\SummaryTasksFormUnit.pas',
  ConstsUnit in 'Common\ConstsUnit.pas',
  FuncUnit in 'Common\FuncUnit.pas',
  KeyValUnit in 'Common\KeyValUnit.pas',
  ParentTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\ParentTaskCustomSettingsEditFrameUnit.pas' {ParentTaskCustomSettingsEditFrame: TUniFrame},
  ConditionUnit in 'EntityClasses\Common\ConditionUnit.pas',
  EntityUnit in 'EntityClasses\Common\EntityUnit.pas',
  GeoTypeUnit in 'EntityClasses\Common\GeoTypeUnit.pas',
  GUIDListUnit in 'EntityClasses\Common\GUIDListUnit.pas',
  StringListUnit in 'EntityClasses\Common\StringListUnit.pas',
  StringUnit in 'EntityClasses\Common\StringUnit.pas',
  TaskSettingsUnit in 'EntityClasses\tasks\TaskSettingsUnit.pas',
  TaskSourceUnit in 'EntityClasses\tasks\TaskSourceUnit.pas',
  TaskTypesUnit in 'EntityClasses\tasks\TaskTypesUnit.pas',
  TaskUnit in 'EntityClasses\tasks\TaskUnit.pas',
  ConnectionSettingsUnit in 'EntityClasses\links\ConnectionSettingsUnit.pas',
  DirSettingsUnit in 'EntityClasses\links\DirSettingsUnit.pas',
  LinkSettingsUnit in 'EntityClasses\links\LinkSettingsUnit.pas',
  LinkUnit in 'EntityClasses\links\LinkUnit.pas',
  QueueSettingsUnit in 'EntityClasses\links\QueueSettingsUnit.pas',
  S3SettingsUnit in 'EntityClasses\links\S3SettingsUnit.pas',
  ScheduleSettingsUnit in 'EntityClasses\links\ScheduleSettingsUnit.pas',
  SummaryTaskCustomSettingsUnit in 'EntityClasses\summary\SummaryTaskCustomSettingsUnit.pas',
  SummaryTaskUnit in 'EntityClasses\summary\SummaryTaskUnit.pas',
  SummaryCXMLTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummaryCXMLTaskCustomSettingsEditFrameUnit.pas' {SummaryCXMLTaskCustomSettingsEditFrame: TUniFrame},
  SummarySynopTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummarySynopTaskCustomSettingsEditFrameUnit.pas' {SummarySynopTaskCustomSettingsEditFrame: TUniFrame},
  SummaryHydraTaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummaryHydraTaskCustomSettingsEditFrameUnit.pas' {SummaryHydraTaskCustomSettingsEditFrame: TUniFrame},
  SummarySEBATaskCustomSettingsEditFrameUnit in 'Forms\TasksFrames\SummarySEBATaskCustomSettingsEditFrameUnit.pas' {SummarySEBATaskCustomSettingsEditFrame: TUniFrame},
  ProfileUnit in 'EntityClasses\datacomm\ProfileUnit.pas',
  RuleUnit in 'EntityClasses\router\RuleUnit.pas',
  SmallRuleUnit in 'EntityClasses\router\SmallRuleUnit.pas',
  OpenMCEPSettingEditFrameUnit in 'Forms\LinksFrames\OpenMCEPSettingEditFrameUnit.pas' {OpenMCEPSettingEditFrame: TUniFrame},
  ParentLinkSettingEditFrameUnit in 'Forms\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  ProfileFrameUnit in 'Forms\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  ProfilesFrameUnit in 'Forms\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  SharedFrameBoolInput in 'Forms\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  SharedFrameCombobox in 'Forms\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameConnections in 'Forms\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameQueue in 'Forms\LinksFrames\SharedFrameQueue.pas' {FrameQueue: TUniFrame},
  SharedFrameTextInput in 'Forms\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  SocketSpecialSettingEditFrameUnit in 'Forms\LinksFrames\SocketSpecialSettingEditFrameUnit.pas' {SocketSpecialSettingEditFrame: TUniFrame},
  DSProcessorTaskUnit in 'EntityClasses\dsprocessor\DSProcessorTaskUnit.pas',
  SelectTaskSourcesFormUnit in 'Forms\SelectTaskSourcesFormUnit.pas' {SelectTaskSourcesForm: TUniForm},
  SourceUnit in 'EntityClasses\dataserver\SourceUnit.pas',
  TasksParentFormUnit in 'Forms\TasksParentFormUnit.pas' {TaskParentForm: TUniForm},
  TaskEditParentFormUnit in 'Forms\TaskEditParentFormUnit.pas' {TaskEditParentForm: TUniForm},
  FilterUnit in 'EntityClasses\Common\FilterUnit.pas',
  common in 'Common\common.pas',
  CompanyUnit in 'EntityClasses\acl\CompanyUnit.pas',
  DepartmentUnit in 'EntityClasses\acl\DepartmentUnit.pas',
  UserUnit in 'EntityClasses\acl\UserUnit.pas',
  DSProcessorTaskEditFormUnit in 'Forms\DSProcessorTaskEditFormUnit.pas',
  DSProcessorTasksFormUnit in 'Forms\DSProcessorTasksFormUnit.pas',
  MonitoringTaskEditFormUnit in 'Forms\MonitoringTaskEditFormUnit.pas',
  MonitoringTasksFormUnit in 'Forms\MonitoringTasksFormUnit.pas',
  HttpRequestUnit in 'APIClasses\HttpRequestUnit.pas',
  DirDownSettingEditFrameUnit in 'Forms\LinksFrames\DirDownSettingEditFrameUnit.pas',
  DirUpSettingEditFrameUnit in 'Forms\LinksFrames\DirUpSettingEditFrameUnit.pas',
  FTPCliDownLinkSettingEditFrameUnit in 'Forms\LinksFrames\FTPCliDownLinkSettingEditFrameUnit.pas',
  FTPCliUpLinkSettingEditFrameUnit in 'Forms\LinksFrames\FTPCliUpLinkSettingEditFrameUnit.pas',
  FTPServerDownLinkSettingEditFrameUnit in 'Forms\LinksFrames\FTPServerDownLinkSettingEditFrameUnit.pas',
  FTPSrvUpLinkSettingEditFrameUnit in 'Forms\LinksFrames\FTPSrvUpLinkSettingEditFrameUnit.pas',
  HTTPCliDownLinkSettingEditFrameUnit in 'Forms\LinksFrames\HTTPCliDownLinkSettingEditFrameUnit.pas',
  Pop3CliDownLinkSettingEditFrameUnit in 'Forms\LinksFrames\Pop3CliDownLinkSettingEditFrameUnit.pas',
  SebaCSDLinkSettingEditFrameUnit in 'Forms\LinksFrames\SebaCSDLinkSettingEditFrameUnit.pas',
  SebaSGSLinkSettingEditFrameUnit in 'Forms\LinksFrames\SebaSGSLinkSettingEditFrameUnit.pas',
  SharedFrameRuleConditionUnit in 'Forms\LinksFrames\SharedFrameRuleConditionUnit.pas',
  SharedFrameS3 in 'Forms\LinksFrames\SharedFrameS3.pas',
  SharedFrameSchedule in 'Forms\LinksFrames\SharedFrameSchedule.pas',
  SMTPClieUpLinkSettingEditFrameUnit in 'Forms\LinksFrames\SMTPClieUpLinkSettingEditFrameUnit.pas',
  SMTPSrvDownLinkSettingEditFrameUnit in 'Forms\LinksFrames\SMTPSrvDownLinkSettingEditFrameUnit.pas',
  BindingUnit in 'EntityClasses\dataserver\BindingUnit.pas',
  ContextTypeUnit in 'EntityClasses\dataserver\ContextTypeUnit.pas',
  ContextUnit in 'EntityClasses\dataserver\ContextUnit.pas',
  DataserieUnit in 'EntityClasses\dataserver\DataserieUnit.pas',
  DsGroupUnit in 'EntityClasses\dataserver\DsGroupUnit.pas',
  SourceCredsUnit in 'EntityClasses\dataserver\SourceCredsUnit.pas',
  SourceTypeUnit in 'EntityClasses\dataserver\SourceTypeUnit.pas',
  RestBrokerBaseUnit in 'APIClasses\RestBrokerBaseUnit.pas',
  AbonentsRestBrokerUnit in 'APIClasses\AbonentsRestBrokerUnit.pas',
  TasksRestBrokerUnit in 'APIClasses\TasksRestBrokerUnit.pas',
  UniversalRestBrokerUnit in 'APIClasses\UniversalRestBrokerUnit.pas',
  AbonentHttpRequests in 'HttpClasses\AbonentHttpRequests.pas',
  BaseRequests in 'HttpClasses\BaseRequests.pas',
  BaseResponses in 'HttpClasses\BaseResponses.pas',
  HttpClientUnit in 'HttpClasses\HttpClientUnit.pas',
  TaskHttpRequests in 'HttpClasses\TaskHttpRequests.pas',
  AliasesRestBrokerUnit in 'APIClasses\AliasesRestBrokerUnit.pas',
  AliasHttpRequests in 'HttpClasses\AliasHttpRequests.pas',
  SummaryTasksHttpRequests in 'HttpClasses\SummaryTasksHttpRequests.pas',
  RuleHttpRequests in 'HttpClasses\RuleHttpRequests.pas',
  RulesRestBrokerUnit in 'APIClasses\RulesRestBrokerUnit.pas',
  TaskSourcesRestBrokerUnit in 'APIClasses\TaskSourcesRestBrokerUnit.pas',
  TaskSourceHttpRequests in 'HttpClasses\TaskSourceHttpRequests.pas',
  HandlersRestBrokerUnit in 'APIClasses\HandlersRestBrokerUnit.pas',
  ProfilesRestBrokerUnit in 'APIClasses\ProfilesRestBrokerUnit.pas',
  QueuesRestBrokerUnit in 'APIClasses\QueuesRestBrokerUnit.pas',
  RouterSourcesRestBrokerUnit in 'APIClasses\RouterSourcesRestBrokerUnit.pas',
  HandlerHttpRequests in 'HttpClasses\HandlerHttpRequests.pas',
  ProfileHttpRequests in 'HttpClasses\ProfileHttpRequests.pas',
  QueueHttpRequests in 'HttpClasses\QueueHttpRequests.pas',
  RouterSourceHttpRequests in 'HttpClasses\RouterSourceHttpRequests.pas',
  BrokerIntfUnit in 'APIClasses\BrokerIntfUnit.pas',
  ChannelsRestBrokerUnit in 'APIClasses\ChannelsRestBrokerUnit.pas',
  ChannelHttpRequests in 'HttpClasses\ChannelHttpRequests.pas',
  CompaniesRestBrokerUnit in 'APIClasses\CompaniesRestBrokerUnit.pas',
  ContextsRestBrokerUnit in 'APIClasses\ContextsRestBrokerUnit.pas',
  DepartmentsRestBrokerUnit in 'APIClasses\DepartmentsRestBrokerUnit.pas',
  LinksRestBrokerUnit in 'APIClasses\LinksRestBrokerUnit.pas',
  SourceCredsRestBrokerUnit in 'APIClasses\SourceCredsRestBrokerUnit.pas',
  SourceTypesRestBrokerUnit in 'APIClasses\SourceTypesRestBrokerUnit.pas',
  CompanyHttpRequests in 'HttpClasses\CompanyHttpRequests.pas',
  ContextsHttpRequests in 'HttpClasses\ContextsHttpRequests.pas',
  DepartmentHttpRequests in 'HttpClasses\DepartmentHttpRequests.pas',
  LinksHttpRequests in 'HttpClasses\LinksHttpRequests.pas',
  SourceCredsHttpRequests in 'HttpClasses\SourceCredsHttpRequests.pas',
  SummaryTasksRestBrokerUnit in 'APIClasses\SummaryTasksRestBrokerUnit.pas',
  SourceTypesHttpRequests in 'HttpClasses\SourceTypesHttpRequests.pas',
  RestEntityBrokerUnit in 'APIClasses\RestEntityBrokerUnit.pas',
  RestFieldSetBrokerUnit in 'APIClasses\RestFieldSetBrokerUnit.pas',
  EntityBrokerUnit in 'APIClasses\Legacy\EntityBrokerUnit.pas',
  DsGroupsBrokerUnit in 'APIClasses\Legacy\DsGroupsBrokerUnit.pas',
  ParentBrokerUnit in 'APIClasses\Legacy\ParentBrokerUnit.pas',
  UsersBrokerUnit in 'APIClasses\Legacy\UsersBrokerUnit.pas',
  BindingsBrokerUnit in 'APIClasses\Legacy\BindingsBrokerUnit.pas',
  SourcesRestBrokerUnit in 'APIClasses\SourcesRestBrokerUnit.pas',
  SourceHttpRequests in 'HttpClasses\SourceHttpRequests.pas';

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
